version: '3.1'

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      
  server:
    build: Sim/
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database

volumes: 
    pgdata: